@startuml ITwordbook

left to right direction
title IT単語帳

[*] --> 起動画面

起動画面 --> 単語一覧画面
起動画面 --> 問題画面
起動画面 --> ログイン画面

単語一覧画面 --> 単語詳細画面 : 単語選択
単語一覧画面 --> 単語登録画面 : 単語登録

単語詳細画面 --> 単語編集画面

問題画面 --> 結果画面 : 結果表示

ログイン画面 --> 会員登録画面 : 新規登録
ログイン画面 --> ログイン完了画面

ログイン完了画面 --> 単語アップロード画面
ログイン完了画面 --> 単語ダウンロード画面


会員登録画面 --> ログイン画面 : 登録完了


@enduml